import { authMiddleware } from "@clerk/nextjs";

export default authMiddleware({
  publicRoutes: [
    "/",
    "/community",
    "/jobs",
    "/question/:questionId",
    "/tags",
    "/tags/:tagId",
    "/profile/:profileId",
    "/assets/icons/account.svg",
    "/assets/icons/arrow-left.svg",
    "/assets/icons/arrow-right.svg",
    "/assets/icons/arrow-up-right.svg",
    "/assets/icons/au.svg",
    "/assets/icons/avatar.svg",
    "/assets/icons/bronze-medal.svg",
    "/assets/icons/calendar.svg",
    "/assets/icons/carbon-location.svg",
    "/assets/icons/chevron-down.svg",
    "/assets/icons/chevron-right.svg",
    "/assets/icons/clock-2.svg",
    "/assets/icons/clock.svg",
    "/assets/icons/close.svg",
    "/assets/icons/computer.svg",
    "/assets/icons/currency-dollar-circle.svg",
    "/assets/icons/downvote.svg",
    "/assets/icons/downvoted.svg",
    "/assets/icons/edit.svg",
    "/assets/icons/eye.svg",
    "/assets/icons/gold-medal.svg",
    "/assets/icons/hamburger.svg",
    "/assets/icons/home.svg",
    "/assets/icons/job-search.svg",
    "/assets/icons/like.svg",
    "/assets/icons/link.svg",
    "/assets/icons/location.svg",
    "/assets/icons/logout.svg",
    "/assets/icons/message.svg",
    "/assets/icons/mingcute-down-line.svg",
    "/assets/icons/moon.svg",
    "/assets/icons/question.svg",
    "/assets/icons/search.svg",
    "/assets/icons/sign-up.svg",
    "/assets/icons/silver-medal.svg",
    "/assets/icons/star-filled.svg",
    "/assets/icons/star-red.svg",
    "/assets/icons/star.svg",
    "/assets/icons/stars.svg",
    "/assets/icons/suitcase.svg",
    "/assets/icons/sun.svg",
    "/assets/icons/tag.svg",
    "/assets/icons/trash.svg",
    "/assets/icons/upvote.svg",
    "/assets/icons/upvoted.svg",
    "/assets/icons/user.svg",
    "/assets/icons/users.svg",
    "/assets/images/site-logo.svg",
  ],
  ignoredRoutes: ["/api/webhook"],
});

export const config = {
  matcher: ["/((?!.+.[w]+$|_next).*)", "/", "/(api|trpc)(.*)"],
};
